version: '3'
services:

  #Laravel App
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather-app
    container_name: application
    volumes: 
      - .:/var/www/
    ports: 
      - "9000:9000"
    networks:
      - laraveldockerize

  #Nginx Service
  my-nginx:
    image: nginx:stable-alpine
    container_name: my-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes: 
      - .:/var/www
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laraveldockerize

#Docker Networks
networks:
  laraveldockerize:
    driver: bridge